name: test

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter tag name for test/dev image'
        default: 'test'

jobs:
  gcr-dockerhub-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update runc (temporary fix) # TODO: Remove step when https://github.com/actions/virtual-environments/issues/2658 fixed
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 3
          retry_on: error
          command: |
            sudo apt-get install libseccomp-dev
            git clone https://github.com/opencontainers/runc
            cd runc
            make
            sudo make install